"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['TestFiles/Main.py']
DATA_FILES = ['TestFiles','RPM_Layer_2','Performance_Optimization_Layer_3','ML_Layer']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
